### ISSUE TITLE
Programs with a lot of dups get stuck

### ISSUE THREAD

**Issue by developedby** [HigherOrderCO/HVM#183]
```
(Func 0 b) = b
(Func a b) = (Func (- a 1) (+ b b))

(Main) = (Func 100000000 2)
```

Running this code with a very large `a`, makes it seemingly never end (expected 10s, waited 10m). Other programs that create lots and lots of dups also seem to cause this.

**Comment by developedby** [comment]
Also it seems this game spends most of the time doing exception handling

**Comment by VictorTaelin** [comment]
Is this for sure related to bugs? I see the program runs normally up to 1m, but performance downgrades quickly after ~4m. I'd guess that's caused by either heap, visit queue or redex bag being overload, so it will be improved only once we have growable memory. That's just a guess though, so I'd appreciate if you could measure the occupancy of each of these structures and report back.

**Comment by developedby** [comment]
Not for sure related to dups strictly, but it does happen with them.

I'll make these measurements and report back

**Comment by developedby** [comment]
Looks like the the visit queue is overflowing in this examples. When that happens, it actually continues storing and reading outside, sometimes at indexes 3x larger than the last position of the stack, before finally freezing or crashing.

Setting the heap to a small value to intentionally cause an overflow also results in similar behaviour.

So the problem here is not the dups, but rather that it accumulates a lot of `(+ b b)` to reduce at once (if I understood correctly what the visit stack is).

The redex bag never gets full. But I found it strange that it always increases its index. What happens if it grows too quickly, will it just overwrite an old unresolved value (and cause incorrect behaviour)?
