### ISSUE TITLE
Comparison to Lunatic

### ISSUE THREAD

**Issue by ShalokShalom** [HigherOrderCO/HVM#258]
Considering both HVM and [Lunatic](https://lunatic.solutions/) are Rust-written platforms, who aim to massively increase parallelism, without the need to change the incoming code - how do the two compare?

Next to the obvious fact, that one does it with Actors, and the other thanks to the Interaction Net. 
HVM seems to need no GC - yey! - and Lunatic is compatible to all Wasm languages. 

Anything else?

**Comment by VictorTaelin** [comment]
Agents based approach are quite standard. HVM attempts to break down programs in the most granular level possible, and parallelize at that level. So, while HVM is fit for the CPU with 10-12 threads (like agents are), in the (near) future we could manage to run it on GPUs and other massively parallel architecture. So, you write a Haskell-like program, you get a massively parallel executable, run it in thousands of threads. That's the ultimate goal of HVM's approach. Right now, though, since agents do a fairly good job at filling the ~16 or so threads that CPUs have, they both should keep all cores busy. Although there is still a difference that agents need to be programmed manually, while HVM is capable of parallelizing everything with no programmer input.

**Comment by ShalokShalom** [comment]
Interesting. Does the calculation on the GPU impose any limits on the type of code, that is written?

I mean, would it be possible to run all on GPU? An OS?

**Comment by zicklag** [comment]
> Interesting. Does the calculation on the GPU impose any limits on the type of code, that is written?

There's a relevant comment here: https://github.com/HigherOrderCO/hvm-core/issues/6#issuecomment-1738377474.

> syscalls can be done via a monadic interface as with other pure functional languages, being on the GPU doesn't prevent that in any way, although it does add some overhead communicating with the CPU. on the ideal, finished runtime, I believe most of the code should run on the CPU, with gthe GPU being an opt-in for specific functions (like, if you're rendering an image using pure recursive functions, you probably want that on the gpu)
