### ISSUE TITLE
Quadaric time & space on heavily shared lazy lists

### ISSUE THREAD

**Issue by oxalica** [HigherOrderCO/HVM#60]
Consider the program calculating `sum (map head (tails list))`. Due to the laziness, though the normal form of `tails list` has `O(n^2)` elements, I'm expecting the whole expression to cost linear time since we don't need to fully evaluate each lazy lists, and the number of elements we actually traversed are just `n`.
But unfortunately, HVM cost quadaric time & space on this scenario, indicating it's not lazy on sub-lists and all sub-lists elements are actually generated.

HVM:
```
(Gen 0) = Nil
(Gen n) = (Cons n (Gen (- n 1)))

(Foldr f z Nil) = z
(Foldr f z (Cons x xs)) = (f x (Foldr f z xs))

(Tails Nil) = (Cons Nil Nil)
(Tails (Cons x xs)) = (Cons xs (Tails xs))

(Map f Nil) = Nil
(Map f (Cons x xs)) = (Cons (f x) (Map f xs))

(Head Nil) = 0
(Head (Cons x xs)) = x

(Main n) = (Foldr @a@b(+ a b) 0 (Map @l(Head l) (Tails (Gen n))))
```

Haskell:
```haskell
import Prelude hiding (head, foldr, tails, map)
import Data.Word (Word32)
import System.Environment (getArgs)

data List a = Nil | Cons a (List a)

gen 0 = Nil
gen n = Cons n (gen (n - 1))

foldr f z Nil = z
foldr f z (Cons x xs) = f x (foldr f z xs)

tails Nil = Cons Nil Nil
tails (Cons x xs) = Cons xs (tails xs)

map f Nil = Nil
map f (Cons x xs) = Cons (f x) (map f xs)

head Nil = 0
head (Cons x xs) = x

main = do
    n <- read . (!! 0) <$> getArgs :: IO Word32
    print $ foldr (\a b -> a + b) 0 (map (\l -> head l) (tails (gen n)))
```

Run time:
| n | HVM (clang, O2, single thread) | GHC, O2 |
|-|-|-|
| 1000 |131ms | 10ms|
| 2000 | 316ms| 10ms|
| 4000 | 1082ms| 12ms|
| 8000 | 5.039s (1.6G mem)| 15ms (5.0M mem)|
|16000|31.018s (5.9G mem)|20ms (5.6M mem)|

I'd think it's a serious issue since it's quite a common pattern to generate lazy data structures and share their parts everywhere (eg. B-Tree, Finger Tree).

**Comment by VictorTaelin** [comment]
That's definitely a serious issue. Today I have a busy day, but as soon as possible I'll investigate why this is happening. Here is the complete reduction of your program for `n = 5`:

https://gist.github.com/VictorTaelin/932520b9219281e4cbc8dd6babc77bab

**Comment by oxalica** [comment]
> I've added a fix to this issue on the quadratic_fix branch, for the interpreted version only. 

Special cased patches seem not enough. Simply repeat the calculation twice, and it's quadratic again.

```
(Main n) =
    let lists = (Tails (Gen n))
    (+ (Sum (Map @l(Head l) lists)) (Sum (Map @l(Head l) lists)))
```

**Comment by oxalica** [comment]
I'd like to see precise reasoning about the time complexity of this evaluation model, instead of find-and-patch, since copying everywhere instead of remembering evaluated state (using "thunk") sounds quite problematic on time complexity. Usually, though copying is lazy, whenever used, data are still copied. So copy-time is just put off to other operations but not eliminated.

Currently there is only "how this is implemented" in HOW.md, but no "how we can achieve the same time (or space) complexity than thunk-based implementation". For generic usage, we should at least convince others that we are at least not worse than others.

**Comment by VictorTaelin** [comment]
It is reasonable to demand proofs about the time complexity of this model, in relation to other models. Note, though, that this isn't "try-and-patch". These reduction rules are well-stablished for decades, and the "patch" above is a well-known optimization, which is safe to apply in some cases. The complexity reasoning comes from the vast literature on the optimal evaluation of programming languages. [This book](https://www.researchgate.net/publication/235778993_The_optimal_implementation_of_functional_programming_languages), from Andrea Asperti and Stefano Guerrini, has a great overview. HVM is merely a practical implementation the bookkeeping-free reduction machine depicted on the book (pages 14-39). There is nothing fancy or invented here. It has a 1-to-1 relationship to the theoretical model, and the same complexity bounds, and respective proofs (chapter 10) apply.

That said, it is surprising, to me, that GHC behaves with superior asymptotical complexity on these inputs. This should not be the case, as far as I understand. So, why this happens? This could be either due to a bug on HVM, or a misunderstanding on my part about the complexity. If it is a bug, we will fix it. If it is a fundamental limitation of the model, then I must understand: *why?* When this occurs? Is this known? Is this something that can be improved? This is a negative result, and that is good. Only by investigating countless "no"s, we can find the most correct "yes"s. Of course, if it turns out that there is no reasonable solution, we must update the docs, and make it clear that HVM isn't *always* asymptotically superior to GHC.

Obviously I can't give you a definite answer right now, but I'll pin this issue to make it clear it is important. This must be throughly understood before moving on.

**Comment by VictorTaelin** [comment]
I wonder what is the complexity of the program below in Haskell, using datatypes, and then using Scott-Encodings. 

```
(Main n) =
    let lists = (Tails (Gen n))
    (+ (Sum (Map @l(Head l) lists)) (Sum (Map @l(Head l) lists)))
```

I'm a little busy today. Can anyone write that program for us?

**Comment by oxalica** [comment]
> It is reasonable to demand proofs about the time complexity of this model, in relation to other models. Note, though, that this isn't "try-and-patch". These reduction rules are well-stablished for decades, and the "patch" above is a well-known optimization, which is safe to apply in some cases.

Sorry for the inappropriate wording since I have not yet fully understood the detail design.

> > Rephrasing [Asperti and Mairson 2001] in this context, [Asperti et al. 2004] showed that the non elementary cost of optimal reduction is not due to bookkeeping (which one may suspect to add superfluous work), but to the (apparently unavoid- able) duplication work. If you accept the fact that optimal reduction performs the minimal amount of duplication, you will have at least the same operations, and hence the same computational cost in any reduction technique. 

Thanks for the reference. I'll check it later. But for this paragraph, I'd interpret it as "it does do duplicated work, though it's minimal (without outside-LC technique)". But GHC uses "thunk" (which cannot be implemented in pure LC) to memorize states of each bindings, ensuing there's actually NO duplicated work at all.

> ... then we must ask: why? When this occurs? Is this known? Is this solvable? This is a negative result, and that is good. Only by investigating countless "no"s, we can find the most correct "yes"s. Of course, if it turns out that there is no reasonable solution, we must update the docs, and make it clear that HVM isn't always asymptotically superior to GHC.

That's also my opinion. It's okay to not beat GHC at every corners. But we should know the exact cases where we are better, and the cases we are not doing well. We should also mention this in README, instead of being advertised as a "generic VM (sometimes) beating GHC".

> I wonder what is the complexity of the program below in Haskell, using datatypes, and then using Scott-Encodings.

Write the same expression twice cost simply twice more time, so the total time complexity is still `O(n)`.
I'm not sure why you want Scott-Encoding, but I'd assume it's referring to [Mogensen–Scott_encoding](https://en.wikipedia.org/wiki/Mogensen%E2%80%93Scott_encoding). But, well, changing encoding doesn't really affect the time complexity.

```haskell
{-# LANGUAGE RankNTypes #-}
import Prelude hiding (head, foldr, tails, map, sum)
import Data.Word (Word32)
import System.Environment (getArgs)

newtype SList a = SList { runList :: forall b. b -> (a -> SList a -> b) -> b }

mkNil = SList (\z cons -> z)
mkCons x xs = SList (\z cons -> cons x xs)

gen 0 = mkNil
gen n = mkCons n (gen (n - 1))

sum xs = runList xs 0 (\x xs' -> x + sum xs')

tails xs = runList xs mkNil (\x xs' -> mkCons xs' (tails xs'))

map f xs = runList xs mkNil (\x xs' -> mkCons (f x) (map f xs'))

head xs = runList xs 0 (\x xs' -> x)

main = do
    n <- read . (!! 0) <$> getArgs :: IO Word32
    print $
        sum (map (\l -> head l) (tails (gen n))) +
        sum (map (\l -> head l) (tails (gen n)))
```

HVM code for comparason:
```
(Gen 0) = Nil
(Gen n) = (Cons n (Gen (- n 1)))

(Foldr f z Nil) = z
(Foldr f z (Cons x xs)) = (f x (Foldr f z xs))

(Tails Nil) = (Cons Nil Nil)
(Tails (Cons x xs)) = (Cons xs (Tails xs))

(Map f Nil) = Nil
(Map f (Cons x xs)) = (Cons (f x) (Map f xs))

(Head Nil) = 0
(Head (Cons x xs)) = x

(Main n) = (Foldr @a@b(+ a b) 0 (Map @l(Head l) (Tails (Gen n))))
```

Evaluation result:

```
> \time cargo r --release -- r tails.hvm 10000
...Omitting cargo outputs...
Reducing.
Rewrites: 100230007 (15.48 MR/s)
Mem.Size: 250135030

99990000
5.95user 0.74system 0:06.71elapsed 99%CPU (0avgtext+0avgdata 1960356maxresident)k
0inputs+0outputs (0major+490681minor)pagefaults 0swaps

> ghc tails.hs -O -o tailsghc && \time ./tailsghc 10000
99990000
0.00user 0.00system 0:00.01elapsed 100%CPU (0avgtext+0avgdata 4784maxresident)k
0inputs+0outputs (0major+477minor)pagefaults 0swaps
```

Note: The definition of `tails` in both Haskell and HVM are not the same as the one in Haskell's `Data.List`, to make it easy to write in HVM. It returns `[[2,1],[1],[]]` for `[3,2,1]`. But the time complexity is the same.

**Comment by VictorTaelin** [comment]
> That's also my opinion. It's okay to not beat GHC at every corners.

Yes, but we need to be clear about that. I do think though that this is achievable; in the worst cases, we could just add references / thunks for these cases where it underperforms. Before going so far, though, I'd rather gain a deeper understanding on the issue, and look for solutions that involve pure rewrite rules.

I asked the Scott-Encoding just for the sake of having the same programs on both the abstract algorithm and GHC (the algorithm of the book doesn't support native datatypes). This gives us an example where the same exact same input performs better on STG. Now we must find out why: maybe it is an issue with my implementation of the algorithm, maybe it is a well known limitation that I somehow missed or just misunderstood, maybe it is something that is actually now known.

**Comment by Mathnerd314** [comment]
I can think of two reasons you're getting quadratic overhead:

* In [Is the Optimal Implementation Inefficient? Elementarily Not](https://drops.dagstuhl.de/opus/volltexte/2017/7733/pdf/LIPIcs-FSCD-2017-17.pdf) they find a quadratic bound on complexity relative to normal order reduction. The quadratic overhead comes from the swap rule (called [Superposed duplication](https://github.com/Kindelia/HVM/blob/master/HOW.md#superposed-duplication) in HVM). But I can't tell from scanning [the gist](https://github.com/Kindelia/HVM/issues/60#issuecomment-1029032865) if that rule is in play here.

* It could just be a space leak. Similarly to how ``sum [1..10^9]`` in unoptimized Haskell builds up a lot of thunks and ends up being slower than a strict language, the program in this issue builds up a lot of duplications. The solution following Haskell is to introduce a "strict evaluate" or `seq` primitive that forces away indirections. Maybe you will also need an `unshare` operation to remove all duplication nodes.

**Comment by VictorTaelin** [comment]
I believe it is pretty likely to be the lack of the safe rules described on the book, which causes an accumulation of redundant dup nodes in some cases. Implementing safe rules on HVM would be an amazing feat.

**Comment by joonazan** [comment]
I skimmed over the literature and it seems to me that optimal reduction is not faster than other strategies in general.

About the efficient reduction of lambda terms claims that the bookkeeping-free version is better in general. However, as evidence it cites Deep into Optimality – Complexity and correctness of sharing implementation of bounded logics, which is bookkeeping-free but only because it operates on bounded logics instead of the general lambda calculus. Is the Optimal Implementation Inefficient? Elementarily Not is restricted to certain linear logics for the exact same reason.

So apart from some confusing papers by Asperti, I'd assume that the status quo is still described by Optimality and inefficiency: what isn't a cost model of the lambda calculus?, which says that an exponential amount of bookkeeping is required regardless of proposed optimizations.

Of course, it could be that there is a way to eliminate bookkeeping but I would probably have seen it on this walk through the literature. The "safe nodes" technique described in Asperti's book that HVM is based on doesn't always work. The book even says in the beginning of chapter 9 that this is still an open problem.

My takeaway is that optimal reduction is not a good approach to performance, and rather than try to find the bookkeeping-free version that might not exist it would make sense to design a good evaluation strategy from scratch. Or use optimal reduction on one of the linear logics that it work on.

**Comment by VictorTaelin** [comment]
You have good points, but I must disagree with your conclusion:

> My takeaway is that optimal reduction is not a good approach to performance, and rather than try to find the bookkeeping-free version that might not exist it would make sense to design a good evaluation strategy from scratch

Which may also not exist. Even if it turns out that this particular example is one where Haskell's STG asymptotically outperforms the HVM, there are countless examples where the opposite is true (and by exponential, not quadratic, margins). So, what do we take from that? Perhaps just like there is no reduction strategy that is best for all cases, perhaps there is no algorithm that is, at all. We may be fighting against a mathematical impossibility here. Or not. Only time will tell.

Now, as for optimal reduction not being a good approach to performance, I find that claim absurd. Rust is widely regarded as performant, and its lambdas are drastically slower than Haskell's. C doesn't even **have** closures. The fact a particular runtime has worse asymptotics than another for specific lambdas doesn't imply that it isn't performant. HVM is lightweight, massively parallel, non garbage-collected and has many other theoretical requirements for a highly efficient language, as the numbers clearly show.

Ultimately, if there turns out to be no "theoretically elegant and perfect" solution to this problem, perhaps a mix of many strategies will end up being adopted. As I said, adding Haskell-like memoized references to HVM wouldn't be hard, which would solve any case where HVM is quadratically slower than GHC. But that would come at a cost of impacting parallelism, confluence, garbage collection freeness, measurability, and other important characteristics, so I wonder if it would be worth it. For example, is the gain above relevant if it impedes us from making massively parallel functional programming processors (which we **can**, for the HVM)?

Finally, note that the algorithm above, and any other similar, can be easily refactored into a much faster version that is really fast on HVM, by using clones more efficiently. I do suspect any instance of a "quadratically slower on HVM" example is a term that uses cloning poorly, and just happens to be handled well by GHC, at the costs above. All in all, mathematics is cruel and sometimes there just isn't a one size fits all answer. I'm not the inventor of the algorithm, all I do is try to implement it efficiently, which I believe is a worthy endeavor, even if it turns out not to work well (which, again, I highly doubt).

**Comment by joonazan** [comment]
Optimal reduction is very good on lambda constructions, which is pretty cool! However, it is still faster to implement integers with machine integers than with lambda constructions. HVM outperforms GHC on certain lambda-heavy programs but that is because Haskell isn't meant to be used that way.

> Finally, note that the algorithm above, and any other similar, can be easily refactored into a much faster version that is really fast on HVM, by using clones more efficiently. I do suspect any instance of a "quadratically slower on HVM" example is a term that uses cloning poorly

As stated by Asperti in one of the papers, programs don't really use higher-order functions a lot. Haskell performs very well on programs with little higher-order action and it is easy to write them.

Eager programming languages are even easier than to write performantly than Haskell. But in return, Haskell gets convenience and even some asymptotic complexity as shown in Okasaki's algorithms book. To sell the more difficult to optimize model, HVM would have to provide something equally desirable.

There are use cases where Haskell could benefit from faster lambdas, for example state monads and other monadic constructions. On the other hand, these things would like to be zero-cost, not just fast.

> Now, as for optimal reduction not being a good approach to performance, I find that claim absurd.

I have already addressed many facets of this but one more is that optimal reduction is not a way to attain utmost performance because it needs a runtime and is interpreted. When aiming for the highest performance, one often has a rough idea about the shape of the desired machine code. An optimal reduction language cannot produce that machine code.

Having no runtime like Rust gives the programmer the freedom to insert a runtime if it is beneficial for some task. There are still some assumptions which are baked into Rust. Most notably, the calling convention and monomorphization via copying or vtables. A perfect language for performance would make even those more malleable.

**Comment by joonazan** [comment]
> Ultimately, if there turns out to be no "theoretically elegant and perfect" solution to this problem, perhaps a mix of many strategies will end up being adopted.

I see some value in a language like this. It reminds me of Python's list and sorting algorithm, which attempt to perform reasonably no matter how they are used. A language that isn't fast but isn't unreasonably slow even if used by a monkey on a typewriter would be very good because it would allow one to write code without thinking about performance at all, only about correctness.

That language isn't possible to actually make but for instance not having to think about using foldr vs foldl would be great.

**Comment by joonazan** [comment]
I'm seeing a bit more overhead than you are.

1. A C function call knows which address to jump to. It doesn't need to go through a jump table, which avoids a branch. This is the part that makes me say this is an interpreter. Also, `reduce` looks like an interpreter to me. That is not how Haskell works.
2. Freeing the memory used by the node is extra work and can probably not be optimized out by any C compiler. C and Haskell's stack is cheaper to manage.

> And why shouldn't it be? In the worst case, it is just a non-garbage-collected version of Haskell's STG.

But optimal reduction is sometimes worse than other reduction strategies. Optimal reduction is a lot slower than Haskell in some cases. And I suspect that slowness isn't as simple to avoid as in Haskell, where it suffices to use data structures rather than huge lambda constructions.

Here's an example of how Haskell code is compiled. I think it is clear from the example that it becomes machine code with jumps, no loop and jump table is involved.
https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/compiler/generated-code#example-1-function-application-with-sufficient-stack-space

**Comment by VictorTaelin** [comment]
> Optimal reduction is a lot slower than Haskell in some cases.

That's a point I don't get. Haskell is a lot slower than optimal reduction in way more cases, and way more profoundly.

**Comment by joonazan** [comment]
First of all, I was not aware that HVM is meant to consume EAL. Partly because EAL wasn't mentioned anywhere and partly because I misread an abstract and thought it said that optimal reduction always outperforms conventional reduction in certain calculi. Now the performance makes a lot more sense.

> As far as I am aware there are no examples anywhere on the internet of a family of terms that requires more n^2 graph reduction steps using optimal reduction vs n for normal order.

Optimal Implementation Inefficient? Elementarily Not proves that a quadratic slowdown is the worst that can happen on ELL and LLL, so that observation matches up with the theory perfectly.

That also explains the example shown in this issue. The README should make it clear that HVM is at best exponentially faster and at worst quadratically slower.

> This is discussed in the [STG paper](https://www.microsoft.com/en-us/research/wp-content/uploads/1992/04/spineless-tagless-gmachine.pdf#page=42). Even STG needs a runtime and an interpreter. They go from while(TRUE) { switch(cont) { ... }} like HVM [uses](https://github.com/Kindelia/HVM/blob/3bd89e86b20177dcc72c2cb6b7c6a8bc7b2a24d2/src/runtime.c#L486) to while (TRUE) { cont = (*cont)*() }. After that they replace the loop indirection with a direct jump, a common JIT optimization. HVM could presumably follow the same path. It just is not very optimized yet.

I can see that the while loop in STG can be trivially turned into direct jumps. It seems to me that HVM cannot know at compile time what the next node is.

>> Optimal reduction is a lot slower than Haskell in some cases.

> That's a point I don't get. Haskell is a lot slower than optimal reduction in way more cases, and way more profoundly.

I'd rather program in a language that has exponential worst cases that are easy to avoid than in a language that has random quadratic pitfalls. Both are bad enough to be unacceptable, so it doesn't matter that one is much worse. Basically I would use HVM if the quadratic performance is easy to avoid or if manipulating big lambda constructions has some benefit other than looking cool.

Did I misread something or do you agree that optimal reduction is sometimes quadratically worse according to the literature? Does anyone have a collection of these poorly performing programs or do we only have the two Github issues?

**Comment by VictorTaelin** [comment]
HVM is not meant to consume EAL though. What he probably means is that EAL is the only subset for which there are proofs of optimal evaluation soundness and efficiency, but it not exhaustive, and indeed is a fairly restrictive subset. For example, EAL doesn't allow Scott Encodings, recursion and the Y-combinator, all that work fine on the HVM. The set of terms HVM can compute soundly and efficiently is massively larger than EAL, and I'd like it to be characterized by a more general extension of EAL.

> The README should make it clear that HVM is at best exponentially faster and at worst quadratically slower.

Yes, I agree, but I'd like to have it reference an actual proof.

> Basically I would use HVM if the quadratic performance is easy to avoid or if manipulating big lambda constructions has some benefit other than looking cool.

I do think that quadratic slowdown is very easy to avoid automatically in most practical cases, though. OP's example is quite artificial `(Map @l(Head l) (Tails (Gen 10)))`, bad code even if it ran linearly, since it is cloning the list repeatedly only to rebuild it.

> Did I misread something or do you agree that optimal reduction is sometimes quadratically worse according to the literature? Does anyone have a collection of these poorly performing programs or do we only have the two Github issues?

I don't have the theoretical knowledge to agree or disagree, I just implemented the algorithm as defined on the literature. As soon as OP raised the issue, I acknowledged and pinned the thread. From what you've been discussed, that seems to be the case.

**Comment by VictorTaelin** [comment]
To add to HVM's performance case: [Kind2](https://github.com/kindelia/kind2)'s dependent type-checker is in late stages of development, and [preliminary benchmarks](https://github.com/Kindelia/Kind2/tree/master/bench) point that it is orders of magnitude faster than Agda's - which, if I'm not mistaken, runs on Haskell via NbE. Once it is more polished, we'll have a complex real-world application to stress test HVM's capabilities.

**Comment by Mathnerd314** [comment]
>  The fairly common expression below  [foo] is exponential on GHC, vs linear on HVM.

Actually with `-O` GHC optimizes this to `foo n = let a = foo (n-1) in a + a` and it is linear. Try again. :-)

**Comment by VictorTaelin** [comment]
> > The fairly common expression below  [foo] is exponential on GHC, vs linear on HVM.
> 
> Actually with `-O` GHC optimizes this to `foo n = let a = foo (n-1) in a + a` and it is linear. Try again. :-)

Not sure it is fair to compare a compiler + a runtime to just a runtime. In theory we could also add a compiler before HVM which also fixed these cases where it is quadratic. My point is STG can't share expressions under λ-binders, which is a pretty substantial drawback for a functional runtime. But again, I'm just explaining the differences that, I believe, are relevant to keep in mind. Both technologies are great pieces of technology, I don't think there is a clear one size fits all winner. If someone thinks GHC works better for certain problem, by all means use it!

**Comment by VictorTaelin** [comment]
Here is a Hacker News comment with my updated thoughts on the issue:

https://news.ycombinator.com/edit?id=35342297

**Comment by Abastro** [comment]
I do not see how it would be easy to avoid these pitfalls for performance, what is the problem here?

**Comment by kings177** [comment]
closing this as HVM is now HVM2.
